//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class Pytanie
    {
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        //public Pytanie()
        //{
        //    this.Odpowiedzi = new HashSet<Odpowiedz>();
        //}
    
        public int IdPytania { get; set; }
        public int NrOdpPop { get; set; }
        public string Tekst { get; set; }

        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Odpowiedz> Odpowiedzi { get; set; }
    }
}
